// Progressive dependency builder. Each adapter goes LIVE when its secret is present, otherwise
// falls back to fixture/mock so the pipeline runs incrementally as you add secrets. With ONLY
// ANTHROPIC_API_KEY set, you get REAL Claude synthesis + REAL fact-gating, with sample news
// (fixture) and mocked publish/Telegram — a true partial-live demo.
import { liveLLM, fixtureLLM } from '../lib/llm/client.mjs';
import { geminiLLM } from '../lib/llm/gemini.mjs';
import { liveJudges, mockJudges } from '../lib/judges/panel.mjs';
import { liveWordPress, mockWordPress } from '../lib/wp/post.mjs';
import { liveTelegram, mockTelegram } from '../lib/notify/telegram.mjs';
import { liveFulltext, mockFulltext } from '../lib/fulltext.mjs';
import { liveCardImage, mockCardImage } from '../lib/img/card_image.mjs';
import { liveDiscover, fixtureDiscover } from './discover.mjs';
import { liveSchedule, fixtureSchedule, liveIntel, fixtureIntel } from './intel.mjs';
import { readSubscriptions, makeSubscriptionMatcher } from '../lib/subscriptions.mjs';
import { rawItems, fixtures, schedule, intel } from '../fixtures/day-2026-06-11/fixture.mjs';

export function buildDeps(env = process.env, { subscriptionsPath } = {}) {
  const has = (...keys) => keys.every((k) => env[k]);
  const mode = {};

  // Synthesis LLM: prefer Anthropic (pinned claude-sonnet-4-6), else Gemini, else recorded fixtures.
  const llm = env.ANTHROPIC_API_KEY
    ? (mode.llm = 'live(anthropic)', liveLLM(env))
    : env.GEMINI_API_KEY
      ? (mode.llm = 'live(gemini)', geminiLLM(env))
      : (mode.llm = 'fixture', fixtureLLM(fixtures));
  // Real news is pulled (RSS) whenever ANY synthesis key is present (the LLM tags entities for
  // clustering). Force fixtures with USE_FIXTURE_NEWS=1.
  const realNews = !env.USE_FIXTURE_NEWS && (env.ANTHROPIC_API_KEY || env.GEMINI_API_KEY);
  const discover = realNews
    ? (mode.discover = 'live(RSS)', liveDiscover(env, llm))
    : (mode.discover = 'fixture(sample news)', fixtureDiscover(rawItems));
  const judges = (env.ANTHROPIC_API_KEY || env.OPENAI_API_KEY || env.GEMINI_API_KEY)
    ? (mode.judges = 'live', liveJudges(env)) : (mode.judges = 'mock', mockJudges());
  const wp = has('WP_SSH_HOST', 'WP_SSH_USER', 'WP_PATH')
    ? (mode.wp = 'live', liveWordPress(env)) : (mode.wp = 'mock', mockWordPress());
  const telegram = has('TELEGRAM_BOT_TOKEN', 'TELEGRAM_GROUP_ID')
    ? (mode.telegram = 'live', liveTelegram(env)) : (mode.telegram = 'mock', mockTelegram());

  const subs = subscriptionsPath ? readSubscriptions(subscriptionsPath) : [];
  const subscriptions = makeSubscriptionMatcher(subs);

  const scheduleDep = (env.SPORTSDATA_API_KEY || env.SERPER_API_KEY)
    ? (mode.schedule = 'live', liveSchedule(env)) : (mode.schedule = 'fixture', fixtureSchedule(schedule));
  const intelDep = (env.SPORTSDATA_API_KEY || env.SERPER_API_KEY)
    ? (mode.intel = 'live', liveIntel(env)) : (mode.intel = 'fixture', fixtureIntel(intel));

  // Full-text enrichment is live whenever we're pulling real news (free, no key).
  const fulltext = realNews
    ? (mode.fulltext = 'live', liveFulltext(env)) : (mode.fulltext = 'off', mockFulltext());

  // Manga-page card art is generated by Gemini; live when GEMINI_API_KEY is present, else a
  // deterministic placeholder (the card still renders + passes glyph-smoke).
  const cardImage = env.GEMINI_API_KEY
    ? (mode.cardImage = 'live', liveCardImage(env)) : (mode.cardImage = 'placeholder', mockCardImage());

  return {
    mode,
    news: { discover, llm, judges, wp, telegram, subscriptions, fulltext, cardImage },
    prematch: { schedule: scheduleDep, intel: intelDep, llm, telegram, subscriptions },
  };
}
